#ifndef WDFILTER_FUNCTIONS_H
#define WDFILTER_FUNCTIONS_H

#include "types.h"
#include "native.h"
#include "io.h"

void _tlgWriteTransfer_EtwWriteTransfer(void *input, uint8_t *input_2, uint64_t input_3, uint64_t input_4, uint32_t input_5, uint64_t *input_6);
uint64_t _tlgKeywordOn(void *input, uint64_t input_2);
void _tlgCreate1Sz_char(WD_EVENT_DATA_DESCRIPTOR *input, int64_t input_2);
void _tlgWriteTemplate__Write(uint64_t input, uint8_t *input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, uint64_t input_7, uint64_t input_8, uint64_t *input_9, uint64_t *input_10, uint64_t input_11, uint64_t input_12, uint64_t *input_13, uint64_t input_14, uint64_t input_15, uint64_t *input_16, uint64_t input_17, uint64_t input_18, uint64_t *input_19, uint64_t input_20, uint64_t input_21, uint64_t *input_22, uint64_t input_23, uint64_t input_24, uint64_t *input_25, uint64_t input_26, uint64_t input_27, uint64_t *input_28, uint64_t input_29, uint64_t input_30, uint64_t *input_31, uint64_t input_32, uint64_t input_33, uint64_t *input_34, uint64_t input_35, uint64_t input_36);
uint32_t MpPostRead(WD_CALLBACK_DATA_VIEW *data, const WD_RELATED_OBJECTS_VIEW *objects, void *completion_context, uint32_t flags);
void WPP_SF_D(uint64_t trace_handle, uint16_t event_id, uint64_t provider, uint32_t value);
void MpPreRead(void *data, void *objects);
void MpPreWrite(WD_LAYOUT_41 *data, void *objects, uint64_t *completion_context);
int64_t MpGetRequestorProcess(void);
int64_t MpGetFileWriteHistoryAndReset__scan(WD_LAYOUT_2 *input, int16_t input_2, void *input_3, WD_LAYOUT_1 *buffer);
void MpPostCreateUpdateStreamContext(void *input, void *input_2, WD_LAYOUT_2 *input_3, uint8_t *input_4, void *context, char input_5);
uint64_t MpSetStreamSize(WD_LAYOUT_2 *input, int16_t input_2, void *input_3, uint64_t input_4);
int32_t MpCreateDlpSectionFileNameEntry(int64_t input, WD_UNICODE_STRING_VALUE *input_2, int64_t *input_3);
void *MpAllocatePoolWithTag(uint32_t pool_type, size_t size, uint32_t tag);
void RtlUnicodeStringCopy(WD_UNICODE_STRING_VALUE *input, WD_UNICODE_STRING_VALUE *input_2);
int32_t GetMpFileStateWithSeq__create(int32_t *input, WD_LAYOUT_42 *input_2);
void ExAllocateFromNPagedLookasideList(void *input);
uint64_t MpPostWrite(WD_LAYOUT_43 *data, void *objects, void *completion_context, uint64_t flags);
uint64_t MpSetStreamState__create(WD_LAYOUT_2 *input, int16_t input_2, void *input_3, uint32_t input_4);
int64_t ExAllocateFromPagedLookasideList(void *input);
uint64_t ExFreeToPagedLookasideList(void *input, uint64_t input_2);
int64_t MpGetStreamSize(WD_LAYOUT_2 *input, int16_t input_2, void *input_3, uint64_t input_4, int64_t *input_5);
uint64_t MpFileTimeToUlong64(uint64_t file_time);
uint64_t MpFileTimeFromUlong64(uint64_t value);
uint32_t MpGetRequestorProcessId(const WD_CALLBACK_DATA_VIEW *data);
int32_t MpGetFileExtensionId(const WD_UNICODE_STRING *extension, uint32_t *extension_id);
uint32_t MpFcKernelGetValue(int32_t input);
int32_t GetMpFileStateWithSeq__cleanup(int32_t *input, WD_LAYOUT_42 *input_2);
uint64_t MpSetStreamState__scan(WD_LAYOUT_2 *input, int16_t input_2, void *input_3, uint32_t input_4);
int32_t RtlULongAdd(uint32_t left, uint32_t right, uint32_t *result);
int64_t MpGetFileWriteHistoryAndReset__create(WD_LAYOUT_2 *input, int16_t input_2, void *input_3, WD_LAYOUT_1 *buffer);
uint32_t MpIsRename(WD_LAYOUT_4 *input);
uintptr_t MpGetRequestorProcessIdEx(const WD_CALLBACK_DATA_VIEW *data);
void *MpAllocatePoolWithQuotaTag(uint64_t pool_type, size_t size, uint32_t tag);
uint64_t MpSetStreamFlag(WD_LAYOUT_2 *input, int16_t input_2, void *input_3, uint32_t input_4, char input_5);
void MpPostMountVolume(int64_t data, void *objects, uint64_t completion_context, uint64_t flags);
void RtlStringCbCopyUnicodeString(uint16_t *input, uint64_t input_2, WD_UNICODE_STRING_VALUE *input_3);
uint64_t RtlStringCbCopyNW(int16_t *input, uint64_t input_2, int64_t input_3, uint64_t input_4);
int32_t RtlULongLongSub(uint64_t left, uint64_t right, uint64_t *result);
uint64_t WPP_SF_(uint64_t input, uint16_t input_2, uint64_t input_3);
void MpSeqDetectCtxGCDpc(uint64_t input, void *input_2);
void MpFltCreateFileEx2(void);
int32_t RtlULongSub(uint32_t left, uint32_t right, uint32_t *result);
int32_t RtlULongToUShort(uint32_t value, uint16_t *result);
void WPP_SF_iD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4);
char MpIsCloudSyncType(void *input);
void WPP_SF_dZZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, int16_t *input_5, int16_t *input_6);
void RtlStringCbLengthW(int16_t *input, uint64_t input_2, int64_t *input_3);
void MpFltCreateFileEx(void);
uint64_t MpSetStreamState__cleanup(WD_LAYOUT_2 *input, int16_t input_2, void *input_3);
void MpMjCreateGetUserSid(WD_LAYOUT_4 *input, int64_t destination_sid);
void RtlStringCbVPrintfExW(uint16_t *input, uint64_t input_2, uint64_t input_3, int64_t *input_4, uint64_t input_5, uint64_t input_6, uint64_t input_7);
void WPP_SF_ZDD(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4);
void WPP_SF_i(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4);
uint64_t MpSetFileWriteHistoryFlag__MpTxF(WD_LAYOUT_2 *input, int16_t input_2, void *input_3);
int32_t RtlStringCbCopyW(int16_t *input, uint64_t input_2, int64_t input_3);
void MpParseFileNameEx(uint16_t *input, int64_t instance, void *input_2, uint16_t *input_3, int64_t *buffer);
void WPP_SF_ZDZDDD(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4, uint64_t input_5, int16_t *input_6);
void McTemplateK0zqqqqxx_EtwWriteTransfer(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4);
void McGenEventWrite_EtwWriteTransfer(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t *input_5);
void RtlStringCchPrintfW(uint16_t *input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qdZidD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, int16_t *input_6);
void MpReferenceObjectByHandle(void);
void WPP_SF_qqD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5);
void RtlStringCchCatW(int16_t *input, uint64_t input_2, int64_t input_3);
void WPP_SF_qidd(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qdddDD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4);
void MpRWLReleaseShared(WD_READ_WRITE_LOCK *lock);
void WPP_SF_IIqq(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, uint64_t input_7);
void WPP_SF_DZ(uint64_t input, uint16_t input_2, uint64_t input_3, uint32_t input_4, int16_t *input_5);
void WppClassicProviderCallback(uint64_t input, uint8_t input_2, uint64_t *input_3, void *input_4);
void WPP_SF_qZZD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5, int16_t *input_6);
void MpTraceAsyncScanQueueExceeded(uint32_t input, uint64_t input_2, uint64_t input_3, char input_4);
uint64_t MpSetEfsHardeningFlags(uint32_t input);
void WPP_SF_ZZZ(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4, int16_t *input_5, int16_t *input_6);
void WPP_SF_qdZiDdDd(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, int16_t *input_6);
void WPP_SF_ZZDd(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4, int16_t *input_5);
void MpSeqDetectCtxShutdown(void);
void WPP_SF_DqSDd(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t input_5, int16_t *input_6);
void WPP_SF_ZZ(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4, int16_t *input_5);
void WPP_SF_ZDDDDDD(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4);
void WPP_SF_qDDDD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_SDP(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4);
void RtlUnicodeStringCopyString(WD_UNICODE_STRING_VALUE *input, int16_t *input_2);
void WPP_SF_DD(uint64_t input, uint16_t input_2, uint64_t input_3, uint32_t input_4);
uint64_t MpDlpBlockActionToNtStatus(WD_LAYOUT_37 *input, int32_t *event_id, uint32_t *input_2);
void MpDeleteDlpSectionFileNameEntry(void *allocation);
void ExSetTimer(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
char ExSetTimerDownlevel(void);
void ExDeleteTimer(uint64_t input, uint16_t *input_2, char input_3, uint64_t input_4);
void ExAllocateTimer(uint64_t input, uint64_t input_2, uint32_t input_3);
uint64_t ExAllocateTimerDownlevel(void);
void EtwSetInformation(uint64_t input, uint32_t input_2, uint64_t input_3, uint32_t input_4);
uint64_t EtwSetInformationDownlevel(void);
void ExAcquirePushLockSharedEx(uint64_t input, uint32_t input_2);
void _invalid_parameter(void);
void ExReleasePushLockSharedEx(uint64_t input, uint32_t input_2);
void ExReleasePushLockExclusiveEx(uint64_t input, uint32_t input_2);
void ExAcquirePushLockExclusiveEx(uint64_t input, uint32_t input_2);
void ExTryAcquirePushLockExclusiveEx(uint64_t input, uint32_t input_2);
void __C_specific_handler(void);
uint64_t memcpy_s(int64_t *buffer, char *buffer_size, uint64_t *input, char *input_2);
uint64_t __GSHandlerCheck(uint64_t input, uint64_t input_2, uint64_t input_3, void *input_4);
void __GSHandlerCheckCommon(uint64_t input, void *input_2, uint32_t *input_3);
uint64_t __cpu_features_init(void);
void __report_gsfailure(uint64_t input);
uint32_t RtlStringCopyWideCharArrayWorker(uint16_t *input, int64_t input_2, int64_t *input_3, int64_t input_4, int64_t input_5);
uint32_t RtlStringCopyWorkerA(char *input, int64_t input_2, int64_t *input_3, int64_t index, int64_t input_4);
uint32_t RtlStringCopyWorkerW(int16_t *input, int64_t input_2, int64_t *input_3, int64_t input_4, int64_t input_5);
uint64_t RtlStringExValidateDestW(int64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
uint64_t RtlStringExValidateSrcW(int64_t *input, uint64_t *input_2, uint64_t input_3, uint32_t input_4);
uint32_t RtlStringLengthWorkerA(char *input, int64_t input_2, int64_t *input_3);
uint32_t RtlStringLengthWorkerW(int16_t *input, int64_t input_2, int64_t *input_3);
uint64_t RtlStringVPrintfWorkerA(int64_t input, int64_t input_2, uint64_t *input_3, char *input_4, uint64_t input_5);
uint32_t RtlStringVPrintfWorkerW(uint16_t *input, int64_t input_2, uint64_t *input_3, uint64_t input_4, uint64_t input_5);
uint64_t RtlStringValidateDestA(uint64_t input, uint64_t input_2, uint64_t input_3);
uint64_t RtlStringValidateDestAndLengthW(int16_t *input, uint64_t input_2, int64_t *input_3, uint64_t input_4);
int32_t RtlUnicodeStringValidateDestWorker(WD_UNICODE_STRING_VALUE *input, int64_t *input_2, uint64_t *input_3, uint64_t *input_4, int64_t input_5, uint32_t input_6);
void RtlUnicodeStringValidateSrcWorker(WD_UNICODE_STRING_VALUE *input, int64_t *input_2, uint64_t *input_3, int64_t input_4, uint32_t input_5);
uint64_t RtlUnicodeStringValidateWorker(WD_UNICODE_STRING_VALUE *input, int64_t input_2, uint32_t input_3);
int64_t RtlWideCharArrayCopyStringWorker(int64_t input, int64_t input_2, int64_t *input_3, int16_t *input_4, int64_t input_5);
uint32_t RtlWideCharArrayCopyWorker(int64_t input, int64_t input_2, int64_t *input_3, uint16_t *input_4, int64_t input_5);
uint32_t _vsnprintf(void);
uint32_t _vsnprintf_l(char *input, uint64_t input_2, char *input_3, uint64_t input_4, uint64_t *input_5);
uint32_t _vsnwprintf(void);
uint32_t _vsnwprintf_l(char *input, uint64_t input_2, uint16_t *input_3, uint64_t input_4, uint16_t *input_5);
uint64_t _flsbuf(uint64_t input, WD_LAYOUT_22 *input_2);
void _output_l(WD_LAYOUT_49 *input, char *input_2, uint64_t input_3, uint64_t *input_4);
void write_char__output(uint8_t input, WD_LAYOUT_49 *input_2, int32_t *input_3);
void write_multi_char__output(uint8_t input, int32_t input_2, WD_LAYOUT_49 *input_3, int32_t *input_4);
void write_string__output(uint8_t *input, int32_t input_2, WD_LAYOUT_49 *input_3, int32_t *input_4);
void _woutput_l(void *input, uint16_t *input_2, uint64_t input_3, uint16_t *input_4);
void write_char__woutput(uint64_t input, void *input_2, int32_t *input_3);
void write_multi_char__woutput(uint16_t input, int32_t input_2, void *input_3, int32_t *input_4);
void write_string__woutput(uint16_t *input, int32_t input_2, void *input_3, int32_t *input_4);
bool _get_printf_count_output(void);
uint64_t _wctomb_s_l(uint32_t *input, int64_t input_2, uint64_t input_3, uint16_t input_4);
uint64_t wctomb_s(void);
uint64_t _fputwc_nolock(uint16_t input, WD_LAYOUT_23 *input_2);
int32_t mbtowc(uint16_t *input, char *input_2, int64_t input_3);
uint64_t _flswbuf(uint64_t input, WD_LAYOUT_22 *input_2);
uint32_t RtlUnicodeToMultiByteN(void);
uint16_t RtlAnsiCharToUnicodeChar(void);
void MpAsyncpShutdownWorkerThreads(uint64_t input, uint64_t input_2, uint64_t input_3);
int32_t MpSendCopyHintTelemetry(void);
void WPP_SF_LiisS(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t input_5, uint64_t input_6, char *input_7, int16_t *input_8);
void WPP_SF_LiisiS(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t input_5, uint64_t input_6, char *input_7, uint64_t input_8, int16_t *input_9);
void WPP_SF_iisS(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, char *input_6, int16_t *input_7);
void WPP_SF_Di(uint64_t input, uint16_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_II(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_Z(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4);
void WPP_SF_dDdZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t input_5, uint64_t input_6, int16_t *input_7);
void WPP_SF_dddZZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t input_5, uint64_t input_6, int16_t *input_7, int16_t *input_8);
void WPP_SF_qDDZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, int16_t *input_7);
void WPP_SF_qDDdqDiiZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qLqZqq(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, int16_t *input_7, uint64_t input_8, uint64_t input_9);
void WPP_SF_qZZ(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5, int16_t *input_6);
void WPP_SF_qqq(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6);
void WPP_SF_qqqiZ(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, uint64_t input_7, int16_t *input_8);
void McTemplateK0qzqqqz_EtwWriteTransfer(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_DDD(uint64_t input, uint16_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_DDDDDDDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_qDD(uint64_t trace_handle, uint16_t event_id, uint64_t provider,
                uint64_t object, uint32_t first_value, uint32_t second_value);
void WPP_SF_qLLLL(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qq(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5);
void WPP_SF_qqDD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5);
void WPP_SF_qqqq(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, uint64_t input_7);
void McTemplateK0x_EtwWriteTransfer(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_ZD(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4);
void WPP_SF_Zi(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4);
void WPP_SF_qDZq(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, int16_t *input_6, uint64_t input_7);
void WPP_SF_qZ(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5);
void WPP_SF_qZq(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5, uint64_t input_6);
void WPP_SF_qZqD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5, uint64_t input_6);
void WPP_SF_qZqDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5, uint64_t input_6);
void WPP_SF_qZqL(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5, uint64_t input_6);
void WPP_SF_qLZ(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, int16_t *input_6);
void MpPostCreateSendFileCreationAsyncMessageIfNeeded(WD_LAYOUT_50 *data, void *objects, void *provider, uint32_t input, char *input_2);
uint64_t MpSetFileWriteHistoryFlag__create(WD_LAYOUT_2 *input, int16_t input_2, void *input_3);
void WPP_SF_S(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4);
void WPP_SF_ZS(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4, int16_t *input_5);
void WPP_SF_ZZD(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4, int16_t *input_5);
void WPP_SF_ZZDS(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4, int16_t *input_5, uint64_t input_6, int16_t *input_7);
void WPP_SF_qDZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, int16_t *input_6);
void WPP_SF_qZD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5);
void WPP_SF_qsDZ(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, char *input_5, uint64_t input_6, int16_t *input_7);
uint64_t MpClearProcessExclusionFlag(void *input);
int32_t MpRegisterFriendlyProcess(uint64_t process_id, int32_t trace_argument_1);
void WPP_SF_LD(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_Zddd(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4);
void WPP_SF_qDDL(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qiLD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qqZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, int16_t *input_6);
void WPP_SF_I(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_ZDd(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4);
void WPP_SF_IDD(uint64_t input);
void WPP_SF_iDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qDqL(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6);
void WPP_SF_qPqL(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6);
void WPP_SF_qZdd(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5);
void WPP_SF_qi(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void McGenControlCallbackV2(uint64_t input, int32_t input_2, char input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, void *input_7);
void McGenEventRegister_EtwRegister(void);
uint64_t McGenEventUnregister_EtwUnregister(void);
void MpReactivateDpc(uint64_t input, int64_t input_2);
void RtlStringCbLengthA(char *input, uint64_t input_2, uint64_t *input_3);
void RtlStringCbPrintfA(char *input, uint64_t input_2, char *input_3, uint64_t input_4);
void WPP_SF_Sd(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4);
void WPP_SF_qS(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5);
void McTemplateK0_EtwWriteTransfer(void);
void McTemplateK0zzx_EtwWriteTransfer(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4);
void MpScanWaitForSemaphores(uint64_t input, WD_LAYOUT_20 *input_2, void *input_3, int64_t input_4, uint32_t *input_5);
uint64_t MpSetStreamUnknownRevertTickcount(WD_LAYOUT_2 *input, int16_t input_2, void *input_3, uint64_t input_4);
void WPP_SF_DZS(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, int16_t *input_5, int16_t *input_6);
void WPP_SF_DiisZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t input_5, uint64_t input_6, char *input_7, int16_t *input_8);
void WPP_SF_SZ(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4, int16_t *input_5);
void WPP_SF_iisZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, char *input_6, int16_t *input_7);
void WPP_SF_qdZiSDDDDDDDiiii(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, int16_t *input_6, uint64_t input_7, int16_t *input_8);
void WPP_SF_Zq(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4, uint64_t input_5);
void WPP_SF_ZqDD(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4, uint64_t input_5);
void WPP_SF_SZZZ(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4, int16_t *input_5, int16_t *input_6, int16_t *input_7);
void WPP_SF_ZDq(uint64_t input, uint16_t input_2, uint64_t input_3, int16_t *input_4, uint64_t input_5, uint64_t input_6);
void WPP_SF_ZZii(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4, int16_t *input_5);
void WPP_SF_ddZZSddS(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t input_5, int16_t *input_6, int16_t *input_7, int16_t *input_8, uint64_t input_9, uint64_t input_10, int16_t *input_11);
void WPP_SF_qLD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qSL(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5);
void RtlUnicodeStringCat(WD_UNICODE_STRING_VALUE *input, WD_UNICODE_STRING_VALUE *input_2);
int32_t MpFsCtlDlpSendServiceMessageTest(void *input);
int32_t MpTerminateEngineProcess(void);
void WPP_SF_dDD(uint64_t input, uint16_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_dDDddii(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_dDZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t input_5, int16_t *input_6);
uint64_t MpObOperationFillSyncData(WD_LAYOUT_52 *input, int64_t *input_2, uint64_t input_3, uint64_t input_4, void *input_5, int32_t *input_6);
void WPP_SF_DDDS(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t input_5, uint64_t input_6, int16_t *input_7);
void WPP_SF_SZZdD(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4, int16_t *input_5, int16_t *input_6);
void WPP_SF_ZDZD(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4, uint64_t input_5, int16_t *input_6);
void WPP_SF_qDddZDZDDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qZDZD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5, uint64_t input_6, int16_t *input_7);
void WPP_SF_qdZDZDdddDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, int16_t *input_6, uint64_t input_7, int16_t *input_8);
void WPP_SF_qddDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qI(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qIZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, int16_t *input_6);
void WPP_SF_qZI(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5);
void McTemplateK0qzqqzxx_EtwWriteTransfer(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_DDqZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t input_5, uint64_t input_6, int16_t *input_7);
void WPP_SF_DZD(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, int16_t *input_5);
void WPP_SF_DZDiis(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, int16_t *input_5);
void WPP_SF_IIIII(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qqZD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, int16_t *input_6);
void WPP_SF_qqZL(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, int16_t *input_6);
void WPP_SF_ZdddiSdd(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4);
void WPP_SF_dSdd(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, int16_t *input_5);
void WPP_SF_dddD(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_qqLqLD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, uint64_t input_7);
void WPP_SF_qqqD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6);
void WPP_SF_qLLL(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qiiL(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_Diiii(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_iii(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_iZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5);
void WPP_SF_iZDD(uint64_t input, uint16_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5);
void WPP_SF_iZDDd(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5);
void WPP_SF_id(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_DdZDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint64_t input_5, int16_t *input_6);
void WPP_SF_ZDDDDD(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4);
void WPP_SF_dDDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_dZD(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, int16_t *input_5);
void WPP_SF_dZDDDDiiiiDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, int16_t *input_5);
void MpFgEventTimerDpc(uint64_t input, void *input_2);
void WPP_SF_ii(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qDi(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void MpPostDirectoryCtrl(void *data, void *objects, uint64_t completion_context, uint64_t flags);
uint64_t MpDlpUpdateEnlightmentForRunningProcesses(uint64_t input, uint64_t input_2);
void WPP_SF_DDDD(uint64_t input, uint16_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_SD(uint64_t input);
void WPP_SF_dD(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_dDd(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_dddd(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4);
void WPP_SF_qDDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void WPP_SF_qZZDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, int16_t *input_5, int16_t *input_6);
void WPP_SF_qqDDZDD(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, uint64_t input_7, int16_t *input_8);
void WPP_SF_qssL(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, char *input_5, char *input_6);
void WPP_SF_ZZDDDDDDDI(uint64_t input, uint64_t input_2, uint64_t input_3, int16_t *input_4, int16_t *input_5);
void WPP_SF_qsZ(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, char *input_5, int16_t *input_6);
void _tlgDefineProvider_annotation__TlgMpWdFilter1DSProviderHandleProv(void);
int64_t CBufferGetNextOffset(WD_LAYOUT_53 *input, uint64_t input_2);
int32_t ComputeEventEntryHash(char input, uint64_t input_2, int64_t input_3);
uint64_t CreateNewEventEntry(char input, uint32_t *input_2, uint64_t input_3, int64_t input_4, char input_5, uint32_t input_6, uint64_t *input_7);
void DestroyEventEntry(WD_LAYOUT_45 *input);
void EnableFlushTimer(int64_t input, uint64_t input_2);
uint64_t ExtractAggregateFieldTypes(uint64_t input, void *input_2);
void FinishHash(int32_t *input);
void FlushLookUpTableBucket(void *input, uint64_t input_2);
uint64_t InsertEventEntryInLookUpTable(uint64_t input, int64_t *input_2, uint64_t input_3, int64_t input_4, uint8_t input_5);
void RunningHash(uint32_t *input, uint8_t *input_2, uint64_t input_3);
void TlgAggregateInternalFlushTimerCallbackKernelMode(int64_t input, void *input_2);
void TlgAggregateInitialize(void);
void _tlgWriteAgg(uint64_t input, uint8_t *input_2, uint64_t input_3, uint64_t input_4, uint64_t *input_5);
void MpTerminateProcess(int64_t input);
void MpQueryRegString(int64_t input, int64_t value_name, int64_t *destination_string);
void MpSetValueKeyString(int64_t input, int64_t input_2, uint16_t *source_string);
void __GSHandlerCheck_SEH(void *input, uint64_t input_2, uint64_t input_3, void *input_4);
uint32_t wcscmp(uint64_t input, uint64_t input_2);
void _guard_dispatch_icall_nop(void);
void _guard_xfg_dispatch_icall_nop(void);
void __security_check_cookie(int64_t input);
void *memcpy(void *destination, const void *source, size_t size);
void *memset(void *destination, int value, size_t size);
uint64_t __memset_repmovs(char *input, uint64_t input_2, int64_t input_3);
uint64_t __memset_query(void);
int32_t memcmp(const void *left, const void *right, size_t size);
void MpSetProcessHardeningExclusion(void *input, int64_t input_2, int16_t *trace_argument_1);
void MpCreateProcessHardeningExcludeDataIfNeeded(void);
void MpResetRunningProcessesHardeningExclusions(uint64_t input, uint64_t input_2);
void MpDumpProcessContext(void);
void MpSetUntrustedProcess(void *input, uint64_t input_2);
uint64_t MpSetProcessInfoFromRequest(void *input);
void MpSetProcessDocOpenRule(WD_LAYOUT_58 *input, int16_t *input_2);
void MpSetDocOpenRule(WD_LAYOUT_58 *input, WD_LAYOUT_57 *input_2);
void MpDeleteProcessExclusionList(int64_t *input);
int32_t MpCreateProcessExclusionList(void *input, int64_t *input_2);
void MpUpdateProcessTrust(void *input);
void MpReleaseProcessContextListEntry(WD_LAYOUT_15 *input);
void MpSetProcessExempt(void *input, int16_t *input_2, bool input_3, int64_t process);
void MpSetTrustedProcess(void *input, uint64_t input_2);
uint64_t MpAllocateProcessContextListEntry(uint64_t *input);
uint64_t MpSetOneProcessInfo(WD_LAYOUT_56 *event_id);
void MpSendHardlinkAsyncMessage(WD_LAYOUT_4 *data, void *objects, void *process_context);
void MpIsUnNamedDataAttribute(WD_LAYOUT_30 *input);
void MpGetRunningProcesses(uint64_t *input, uint32_t *input_2);
void MpGetProcessContextList(int64_t *input, bool input_2);
void MpGetFileAttributes(void *input);
uint64_t MpGetProcessContextByIdAndCreationTime(uint64_t input, int64_t input_2, int64_t *input_3);
void MpDlpGetProcessContextFromTokenAttribute(int64_t input, int64_t *process_context);
void MpCopyCacheSetTimeStamp(void *input, int64_t input_2, int64_t input_3);
void MpCopyCacheSetFileSize(void *input, int64_t input_2, int64_t input_3);
void MpQueryObjectName(int64_t object, uint64_t *name);
void MpPostSetInfo(void *data, uint64_t *objects, int64_t *completion_context, uint64_t flags);
void MpDlpGetAccessCheckProcessContext(int64_t input, int64_t *input_2);
int32_t MpGetProcessContextByObject(uint64_t process, int64_t *input);
uint64_t MpObPreOperationCallback(uint64_t input, void *input_2);
void MpObHandleOpenDesktopCallback(WD_LAYOUT_60 *input);
void MpObHandleOpenProcessCallback(WD_LAYOUT_63 *input);
uint64_t MpPostCleanup(uint64_t data, void *objects, WD_LAYOUT_64 *completion_context, uint32_t flags);
void MpGetUsn(uint64_t input, void *input_2, uint16_t input_3);
void MpObSendOpenProcessBMNotification(uint64_t input, int64_t input_2, void *input_3, int64_t input_4, uint32_t input_5, uint32_t input_6, char input_7, char input_8);
void MpDlpOnFileObjectClose(void *input, WD_LAYOUT_65 *input_2, uint64_t input_3, int32_t input_4, char input_5, uint32_t input_6);
void MpAsyncCreateNotification(int64_t *input, uint32_t input_2);
int32_t MpSendFileAsyncMessage(uint32_t input, void *data, void *input_2, uint32_t input_3, uint32_t input_4, uint32_t input_5, int64_t input_6, uint16_t *input_7, void *input_8, uint64_t *input_9, uint64_t *input_10);
void MpCreateFileAsyncMessage(uint64_t *input, uint32_t *input_2, uint32_t input_3, void *data, void *input_4, uint32_t input_5, uint32_t input_6, uint32_t input_7, int64_t input_8, uint16_t *input_9, void *input_10, uint64_t *input_11, int64_t input_12, uint64_t *input_13);
void MpQuerySessionId(uint64_t input, uint64_t input_2, uint32_t *input_3);
int64_t *MpAsyncSendNotification(WD_LAYOUT_6 *input, uint32_t input_2, int32_t input_3, uint32_t input_4, void *input_5);
void MpAsyncDereferenceNotification(WD_LAYOUT_5 *input);
void MpSendProcessMessage(char input, int64_t input_2, int64_t input_3, uint64_t process_id, uint32_t input_4, int64_t input_5, int64_t *input_6, uint16_t *input_7, void *input_8, WD_UNICODE_STRING_VALUE *input_9, char *input_10);
void MpSetProcessInfoByContext(void *input, void *event_id, uint64_t provider);
int32_t MpRegpSendNotification(void *input, WD_LAYOUT_67 *input_2);
uint64_t MpShouldSendBmMessage(void *input);
uint32_t MpRegpCalculateNotificationSize(void *input, uint32_t *input_2, int32_t *input_3);
uint64_t MpRegpCopyVariableNotificationData(void *input, int16_t *input_2, uint32_t input_3, uint32_t input_4);
uint32_t MpRegpCopyBufferToNotification(uint64_t *input, int64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t *input_5, uint64_t *input_6);
int32_t MpRegPostDeleteValueKey(WD_LAYOUT_70 *input, WD_LAYOUT_69 *input_2);
int32_t MpRegPostSetValueKey(WD_LAYOUT_72 *input, WD_LAYOUT_71 *input_2);
void MpRegpFreeCallContext(int64_t input);
void MpQueryTransactionId(int64_t input, uint32_t *input_2);
int32_t MpRegPostDeleteKey(WD_LAYOUT_70 *input, uint64_t input_2, WD_LAYOUT_74 *input_3);
void MpDlpPreCreate(int64_t data, WD_LAYOUT_39 *input, WD_LAYOUT_75 *input_2);
void MpHardenSectorWrites(void *input, WD_LAYOUT_76 *input_2);
void MpHardenPathOnPreCreate(void *data, WD_LAYOUT_76 *input, uint64_t *input_2, uint64_t *input_3);
int32_t MpRegPostCreateKeyEx(WD_LAYOUT_72 *input, uint64_t input_2, WD_LAYOUT_80 *input_3);
void MpHardenPageFileCreate(void *data, WD_LAYOUT_76 *input);
void MpAddECP(uint64_t input, uint64_t input_2, uint32_t buffer_size, int64_t input_3);
void MpPreCreate(void *data, void *objects, uint64_t *completion_context);
void MpRegCallback(uint64_t input, uint64_t input_2, int64_t *input_3);
uint64_t MpDlpIsEnabled(int64_t input, WD_LAYOUT_17 *input_2);
void MpDlpRegistryCallback(int32_t input, WD_LAYOUT_72 *input_2, int64_t *input_3);
void MpPreCleanup(void *data, uint64_t *****objects, uint64_t *completion_context);
void MpDlpPreCleanup(uint64_t data, void *input, void *input_2);
uint64_t MpReleaseProcessContext(void *context);
void MpCreateThreadNotifyRoutine(uint64_t process_id, int64_t input, bool input_2);
void MpPreSectionSyncPPLReduxCallback(void *data, void *input);
void MpRegHardenningBlockOperation(int64_t input, WD_LAYOUT_30 *input_2, int64_t input_3, uint64_t *input_4, int64_t *input_5, char *input_6, char *input_7);
uint64_t MpIsRegistryHardeningExemptByContext(void *input);
void MpAsyncScanWorkerThread(uint64_t trace_argument_1);
uint64_t MpAsyncScanDequeue(int64_t *input);
void MpCleanupScanRequestContext(int64_t *input);
void MpDoScanFile(void *input);
bool MpSeqDetectCtxCheck(uint64_t input, uint64_t input_2);
uint64_t MpSeqDetectCtxLookupEntry(uint64_t input, uint64_t input_2);
void MpScanFile(int64_t input, void *data, void *input_2, int32_t input_3, uint32_t input_4, uint16_t *input_5, uint64_t *input_6, uint32_t input_7, uint64_t *input_8, void *input_9, int64_t input_10, void *input_11);
void MpAmPostCreate(void *data, void *objects, WD_LAYOUT_93 *input, uint64_t input_2, int64_t *input_3);
void MpUpdateHandleContextOnPostCreate(WD_LAYOUT_4 *input, WD_LAYOUT_88 *input_2, WD_LAYOUT_90 *input_3, int64_t *input_4);
void MpCreateHandleContext(void *input, uint64_t *input_2, char *input_3);
void MpCopyStreamStateFromFileStateGenericTable(void *input, uint64_t input_2, int64_t input_3);
void MpCreateStreamContext(void *data, void *input, uint8_t *input_2, uint64_t input_3, char input_4, uint64_t *input_5);
int32_t MpDlpRegisterForPolicyUpdate(WD_PROCESS_REFERENCE_VIEW *input, WD_UNICODE_STRING_VALUE *input_2, void *input_3, uint32_t input_4);
void MpDlpSetProcessEntryFlags(int64_t data, void *input, WD_LAYOUT_17 *input_2, void *input_3, char *input_4, uint32_t input_5, uint32_t input_6);
int32_t MpCreateDlpProcessEntry(WD_PROCESS_REFERENCE_VIEW *input, WD_UNICODE_STRING_VALUE *input_2, int64_t *input_3);
void MpDeleteDlpProcessEntry(void *allocation);
uint64_t MpCopyCacheMatch(WD_LAYOUT_85 *input, int64_t input_2, int64_t input_3, int64_t input_4, uint64_t *input_5, char *input_6);
void IsThisCallBeingThrottled(void);
void MpDlpSetEaOnDestination(WD_LAYOUT_85 *input, void *input_2, WD_LAYOUT_86 *information_buffer, void *input_3, int16_t *input_4, char input_5, char input_6);
void MpQueryNetworkOpenInformation(void *input, WD_LAYOUT_86 *information_buffer);
void MpCreateThreadNotifyRoutineEx(int64_t process_id, uint64_t input, bool input_2);
int32_t MpFreeString(void *string);
void MpTraceRegHardeningNotification(int32_t input, char input_2, void *input_3, int64_t input_4, uint32_t *input_5, uint32_t *input_6, uint32_t *input_7);
void MpRegpAllocDeleteKeyContext(void);
void MpRegpQueryValueKeyByPointer(uint64_t input, uint64_t value_name, uint32_t *input_2, uint64_t *input_3);
WD_LAYOUT_94 *MpRegpAllocDeleteValueContext(void);
WD_LAYOUT_94 *MpRegpAllocSetValueContext(void);
uint64_t MpRegTPAllowChange(void *input, int16_t *trace_argument_3, int64_t *input_2);
void MpRegPreDeleteKey(int64_t *input, uint64_t input_2, int64_t *input_3, char *input_4, int64_t *input_5);
uint16_t *MpRegpCopyUnicodeString(void *source_string, uint64_t *input);
void MpRegPreDeleteValueKey(WD_LAYOUT_95 *input, uint64_t input_2, int64_t *input_3, char *input_4, void *input_5);
void MpRegpMatchName(uint16_t *source_text, WD_LAYOUT_65 *input);
void MpRegPreSetValueKey(WD_LAYOUT_96 *input, uint64_t input_2, int64_t *input_3, char *input_4, int64_t *input_5);
void MpRegMatchData(uint16_t *input, WD_LAYOUT_65 *input_2, uint64_t input_3, int64_t *input_4);
int32_t MpRegpMatchEntry(void *input, uint64_t input_2, WD_LAYOUT_65 *input_3, int16_t *input_4, int64_t *input_5);
void MpRegpMatchUserClasses(WD_LAYOUT_65 *input);
void MpRegpGetKeyName(int64_t input, uint64_t *input_2);
uint64_t MpRegAddMatches(WD_LAYOUT_26 *input, uint64_t *input_2);
void MpRegPreCreateKeyEx(int64_t input, uint64_t input_2, int64_t *input_3, char *input_4, uint64_t input_5, uint8_t input_6);
void MpRegpCheckExistingKey(WD_LAYOUT_30 *input, char *input_2, int64_t *input_3);
int32_t MpAppendUnicodeStringToUnicodeString(WD_LAYOUT_10 *input, uint16_t *input_2, uint64_t *input_3, uint32_t pool_tag);
void MpRegpParseInfiniteWildcard(int64_t *input, int64_t *input_2, WD_LAYOUT_19 *input_3);
void MpRegPreSetKeySecurity(int64_t *input, uint64_t input_2, int64_t *input_3, char *input_4, void *input_5);
int64_t *MpRegpPushEntryToStack(int64_t *input, int64_t input_2, WD_LAYOUT_83 *input_3);
void MpRegpAllocCreateKeyContext(void);
void MpGetDlpStubFileNameForNetworkFile(WD_LAYOUT_97 *input, WD_LAYOUT_98 *input_2, uint64_t *input_3);
void MpHashDataBuffer(int64_t buffer, int32_t size, uint32_t *hash);
void MpHashLibInitIfNeeded(void);
uint64_t MpAllocateString(uint16_t input, int64_t *input_2);
int32_t MpGetDlpDefaultStubFileName(WD_LAYOUT_98 *input, uint64_t *input_2);
void MpAsyncpWorkerThread(void);
void MpAsyncpSendMessage(int64_t input, int32_t input_2, uint64_t input_3);
uint64_t MpDlpShouldReportRename(uint32_t input);
void MpIsThisPrefetchOperation(void *input, int64_t *input_2);
uint64_t MpTxfResolveTransaction(WD_LAYOUT_34 *input, WD_LAYOUT_33 *input_2, uint64_t *input_3, int64_t *input_4, char *input_5);
void MpCopyCacheOnPostCreate(int64_t data, void *input, void *input_2, void *input_3);
void MpTxfGetContext(void *input, bool input_2, int64_t input_3, uint64_t *input_4);
void MpSeqDetectCtxUpdate(uint64_t input, uint64_t input_2, int64_t input_3, int64_t *input_4, uint32_t input_5, char *input_6);
void MpUpdateFileWriteHistory(void *input, void *input_2, void *input_3, WD_LAYOUT_2 *input_4, int64_t *input_5);
void MpPreFsControl(void *data, void *objects, int64_t *completion_context);
void MpFsCtlDispatcher(WD_LAYOUT_4 *data, void *input);
void MpPreSetEncryption(void *data, void *input);
void MpPreFileLevelTrim(void *data, void *input);
void MpCheckForAmHardening(void *input, WD_LAYOUT_76 *input_2, int64_t input_3, void *input_4, char input_5);
void MpHardenPathOnPostCreate(void *data, void *input, WD_LAYOUT_78 *input_2, uint64_t *input_3);
void MpCheckLoopbackOnPostCreate(WD_LAYOUT_4 *data, void *input, uint64_t *input_2);
void FsHardeningMatch(void *file_name, uint16_t *file_name_2, uint16_t *extension, int64_t file_object, void *input, uint64_t input_2, uint32_t *input_3);
void MpIsAMPath(WD_LAYOUT_78 *input, void *file_name, int16_t *input_2);
void MpApplyFolderGuard(WD_LAYOUT_4 *input, void *input_2, void *input_3, WD_UNICODE_STRING_VALUE *input_4, char input_5);
void MpFgIsFileProtected(WD_LAYOUT_79 *input, uint64_t input_2);
void MpIsLoopbackByObj(void *input, int64_t file_object, uint8_t *input_2);
void MpFgSendNotification(void *input, WD_UNICODE_STRING_VALUE *input_2, char input_3);
void MpDlpQueryEaEx(WD_LAYOUT_4 *input, void *input_2, WD_LAYOUT_32 *input_3, char *input_4);
void MpDlpQueryEa(WD_LAYOUT_4 *input, int64_t instance, int64_t file_object, WD_LAYOUT_32 *input_2, char *input_3);
void MpDlpAtomicCheckFileAndOperationAccess(WD_LAYOUT_4 *data, void *input, void *input_2, uint32_t input_3, uint64_t input_4, void *input_5, uint32_t *input_6);
void MpIsLoopbackByName(void *input, void *file_name, uint8_t *input_2, int64_t *input_3, uint64_t *input_4);
uint64_t MpInitializeKnownProcessPaths(void);
void MpGetSystemFolderPath(uint64_t source_text, uint64_t *name);
void MpIsVolumeOnCsvDisk(uint64_t input);
void MpInstanceSetup(void *input, uint64_t input_2, uint32_t input_3, int32_t input_4);
void MpCreateInstanceContext(void *input, uint8_t input_2, int32_t input_3, int32_t input_4);
void MpInitFileStateGenericTable(void *input, int32_t input_2, uint32_t input_3);
void MpIsSystemVolume(uint64_t input, char *input_2);
void MpGetVolumeProperties(WD_LAYOUT_45 *input, void *input_2);
void MpScanBootSector(int64_t input, void *input_2, int32_t input_3, char *input_4, int64_t *input_5);
char MpIsProcessExemptByData(void);
void MpIsHotPluggable(WD_LAYOUT_45 *input);
void MpGetProcessContextById(int64_t process_id, int64_t *input);
uint64_t MpIsProcessExemptById(int64_t process_id);
void MpIsGoodBootSector(int64_t input, uint64_t input_2);
void MpReadRawDevice(uint64_t input, uint64_t input_2, uint64_t input_3, uint32_t input_4, uint32_t input_5);
void MpGetPriorityInfo(uint64_t input, uint64_t input_2, WD_LAYOUT_26 *input_3);
void MpGetStorageDeviceAttributes(WD_LAYOUT_45 *input, uint64_t *input_2);
uint64_t MpCreateBootScanContext(int64_t input, uint32_t input_2, uint64_t *input_3);
void SwitchOffPanicMode(uint64_t input);
uint64_t MpAllowCodeInjection(void *input, void *input_2, uint64_t input_3);
uint64_t MpIsProcessExemptByContext(WD_LAYOUT_44 *input);
void MpDlpUpdatePolicyWorker(int64_t input, uint64_t input_2, int64_t ****context);
void MpDlpUpdateFilePolicy(void *input, void *input_2, WD_LAYOUT_65 *input_3, uint32_t input_4, int32_t input_5, uint64_t *input_6, uint32_t input_7);
void MpDlpQueryService(uint32_t input, void *input_2, uint32_t *input_3, uint32_t *input_4);
void MpSendAsyncDirectoryNotification(WD_LAYOUT_4 *data, void *input, int32_t input_2, char *input_3);
void MpPreSetInfo(void *data, void *objects, int64_t *completion_context);
void MpHardenPathOnRenameLink(void *input, void *input_2);
void MpIsDirectory(void *input);
uint64_t MpGetMappedPurgeExclusionLock(void *input, int64_t *input_2);
void MpScanOnPreUserModeReadCopySourceFile(WD_LAYOUT_28 *data, void *input, int64_t *input_2, int64_t *input_3, uint8_t input_4);
uint64_t MpValidateAndReferenceStream(WD_LAYOUT_102 *input, uint64_t *input_2, uint64_t *input_3, bool input_4);
void MpGetFileIdAndUsnFromFileObject(uint64_t input, uint64_t input_2, uint64_t input_3, int64_t *input_4);
void MpQueryEaFile(int64_t input, void *input_2, int32_t input_3);
void MpGetStreamContextFromFileObject(uint64_t file_object, uint64_t *stream_context);
void MpGetInstanceFromFileObject(uint64_t input, uint64_t *input_2);
char MpCompareFileStateGenericTableEntry(uint64_t input, int64_t *input_2, int64_t *input_3);
void MpUpdateFileSize(WD_LAYOUT_4 *input, void *input_2, void *input_3, WD_LAYOUT_2 *input_4, uint64_t *input_5);
void MpDeleteHandleContext(void *context, int16_t context_type);
void MpDeleteStreamContext(void *context, uint64_t context_type);
void MpSaveStreamStateToNtfsCache(void);
void MpSaveStreamStateToRefsCache(void);
void MpSaveStreamStateToCsvCache(void *input);
void MpSaveStreamStateToFileStateGenericTable(void *input, int32_t trace_argument_1, uint32_t input_2, int64_t input_3, uint32_t input_4, uint64_t *input_5);
uint64_t MpDlpProcessRemoveSensitiveSectionFromRunningProcesses(int64_t input, uint64_t input_2);
uint64_t MpDlpProcessRemoveSensitiveSectionFile(WD_LAYOUT_103 *input, int64_t input_2);
uint64_t MpDuplicateString(WD_UNICODE_STRING_VALUE *source_string, int64_t *input);
void MpRegUpdateData(uint64_t input, WD_LAYOUT_104 *input_2);
uint64_t MpRegpValidateUserModeData(uint32_t input, uint32_t *input_2);
uint64_t MpValidateDocOpenUserData(uint32_t input, uint32_t *input_2);
int32_t MpCreateDocOpenRules(uint32_t *input, int64_t *input_2);
int32_t MpConvertMultiSzOffsetToPointer(uint64_t input, uint64_t trace_argument_3, int64_t provider, uint32_t left, uint32_t *result, uint64_t *input_2);
int64_t MpMultiStringCbLen(int16_t *input);
int32_t MpRegpProcessValueList(uint64_t input, uint64_t trace_argument_3, uint64_t input_2, uint64_t input_3, int64_t *******input_4, int64_t *input_5);
int32_t MpRegpProcessUserModeData(uint32_t input, WD_LAYOUT_104 *event_id, uint32_t *provider, uint64_t *input_2);
int32_t MpRegpProcessClientList(uint64_t input, uint64_t trace_argument_3, uint64_t input_2, uint64_t input_3, uint32_t *input_4, uint64_t *input_5);
int32_t MpConvertOffsetToPointer(uint64_t input, uint64_t trace_argument_3, int64_t provider, uint32_t right, uint32_t left, uint32_t *result, uint64_t *input_2);
int32_t MpConvertStringOffsetToPointer(uint64_t input, uint64_t trace_argument_3, int64_t provider, uint32_t input_2, uint32_t input_3, uint32_t *result, uint64_t *input_4);
void MpReleaseDocOpenRule(void *input);
void MpDeleteDocOpenRules(int64_t *input);
uint64_t MpFcKernelUpdateFeatureControlsFromRequest(void *input);
void MpFcKernelLogFeatureControls(uint32_t *pool_type);
void MpTraceLogBindFltHardeningChanged(int32_t input, int32_t input_2);
void MpRemoveWriteAccess(WD_LAYOUT_4 *input);
int32_t MpQueryRuntimeDrivers(void *input, uint64_t *event_id, WD_LAYOUT_109 *provider, uint32_t input_2, uint32_t *input_3);
void MpLogPrintfW(int16_t *input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void MpDeleteWriteContext(void *input);
uint64_t MpDlpGetProcessEntryFlags(WD_LAYOUT_29 *input, int64_t input_2, uint32_t *input_3);
uint64_t MpCreateWriteContext(WD_LAYOUT_36 *input, int64_t input_2, uint64_t input_3, uint64_t *input_4);
uint64_t MpQueryKnownBadTable(void *input, uint32_t input_2);
uint64_t IsFileDirty(WD_LAYOUT_2 *input, int16_t input_2, void *input_3);
void MpFsCtlQueryNormalizedName(void *data, void *input);
void MpDlpPreAcquireSectionSync(void *data, void *input, void *input_2);
void MpDlpCheckFileAccess(void *input, void *input_2, void *input_3, uint32_t input_4, void *input_5, void *input_6, uint8_t *input_7, uint32_t input_8, int64_t input_9, uint64_t input_10);
void MpQueryFileName(uint64_t data, uint64_t input, int64_t *input_2, char *input_3);
void MpRedirectionEcpContextInitializer(uint16_t *input);
uint64_t MpDlpLoadProcessModuleNotifyRoutine(WD_LAYOUT_14 *input, WD_UNICODE_STRING_ADDRESS_VIEW *source_string);
uint64_t MpSuffixUnicodeString(WD_UNICODE_STRING_POINTER_VIEW *input, WD_UNICODE_STRING_ADDRESS_VIEW *input_2);
void MpPreQueryEa(void *data, void *objects, uint64_t *completion_context);
void MpQueryEaFromNetworkFileStubIfNeeded(void *data, void *input, uint64_t *input_2);
void MpCreateSection(void *input, void *input_2);
void MpSuppressFileAccessTimeUpdateIfNeeded(WD_LAYOUT_20 *input, int64_t input_2, WD_LAYOUT_107 *input_3);
void MpFindAckedECP(uint64_t input, uint64_t input_2, uint64_t *input_3, uint32_t *input_4);
void MpReferenceProcessContext(WD_PROCESS_REFERENCE_VIEW *context);
void MpSeqDetectGCWorker(WD_LAYOUT_48 *input);
uint64_t MpQueryMotwAds(void *input, void *input_2);
void MpFileHasMotwAds(uint64_t file_object, WD_LAYOUT_20 *input);
void MpCreateProcessNotifyRoutineEx(int64_t process, uint64_t process_id, void *provider);
void MpHandleProcessNotification(int64_t process, int64_t process_id, uint64_t process_id_2, bool input, uint32_t input_2, int64_t file_object, int16_t *trace_argument_1, WD_UNICODE_STRING_VALUE *input_3, char *input_4);
uint64_t MpGetImageNormalizedName(int64_t input, uint64_t input_2, uint64_t file_name);
uint64_t MpCheckForFolderGuard(uint64_t input, uint64_t input_2, void *input_3);
uint64_t MpIsPotentialRemoteOpen(WD_LAYOUT_4 *input);
void MpRegpFreeUnicodeString(int64_t allocation);
void MpQuerySessionIdFromObjects(int64_t input, int64_t input_2, WD_LAYOUT_3 *input_3, uint32_t *input_4);
void MpQuerySessionIdFromProcess(int64_t input, uint64_t process_id, uint32_t *input_2);
void MpQuerySessionIdToken(int64_t token, uint32_t *input);
uint64_t HandleMpScanFileResult(uint32_t *input, int32_t input_2, WD_LAYOUT_28 *input_3, uint64_t input_4, void *input_5, char input_6);
void MpPreQueryOpen(void *data, void *objects);
char MpRegHardeningIsMatch(uint64_t input);
void MpRegpFreeKeyName(WD_LAYOUT_4 *input);
uint64_t MpIsObHardeningExemptByContext(void *input);
void MpMatchPerServiceSidByObj(int64_t input, int64_t input_2);
void MpCheckTokenMembership(int64_t input, uint64_t input_2, char *input_3);
uint64_t MpAllowAccessBasedOnHipsRule(void *input, void *event_id, uint32_t provider, uint32_t input_2, uint32_t input_3, char *input_4);
void MpDeleteSectionContext(uint64_t context, int16_t context_type);
void MpClearFileStateGenericTableList(uint64_t *input);
void MpDeleteInstanceContext(void *context, int16_t context_type);
void MpFreeFileStateGenericTable(void *input, int32_t input_2);
void MpPurgeCache(uint64_t input, uint64_t input_2);
void MpClearFileStateGenericTable(int64_t *input);
void MpPurgeScannedFileCache(void *trace_argument_2, WD_LAYOUT_24 *event_id, uint64_t provider);
void MpPurgeFileStateGenericTable(void *input, uint64_t input_2, WD_LAYOUT_24 *input_3);
void MpQueryTargetFileName(WD_LAYOUT_4 *input, void *input_2, uint32_t input_3, int32_t input_4, char input_5, int64_t input_6, char *input_7);
int32_t MpRegpCopyStringToNotification(int16_t *input, int64_t input_2, uint64_t destination_size, WD_LAYOUT_65 *input_3, int64_t *input_4);
uint64_t MpDlpIsProtectedProcess(void *input);
void MpSetProcessHardening(int64_t input, void *input_2, int16_t *trace_argument_1);
void MpRegpFreeSetValueContext(void *input);
int32_t MpRegPostSetKeySecurity(WD_LAYOUT_70 *input, uint64_t input_2, WD_LAYOUT_74 *input_3);
int32_t MpInitializeCsrssHookDataIfNeeded(void);
int32_t MpRegpCalculateNextOffset(uint64_t input, uint64_t left, uint64_t right, uint64_t *input_2, int64_t *result);
uint16_t MpIsRenameOrLinkTargetPossibleSymLink(int64_t input, uint32_t input_2, int16_t *input_3);
void MpGetRenameParentTargetSymLinkNameInformation(int64_t input, void *input_2, bool input_3, uint64_t input_4, void *input_5, uint32_t name_options, uint64_t *file_name, uint64_t *input_6, int64_t *destination_string);
void MpQueryLoopbackLocalPathByFileObject(WD_LAYOUT_76 *input, int64_t input_2, uint64_t *input_3, int64_t *destination_string);
void MpQueryLoopbackEa(WD_LAYOUT_76 *input, uint64_t input_2, uint64_t *input_3);
void MpFreeFileStateGenericTableEntry(uint64_t input, uint64_t allocation);
void MpRegpFreeDeleteValueContext(void *input);
void MpSendSyncMonitorNotification(int32_t input, WD_LAYOUT_66 *input_2, uint16_t *input_3, WD_LAYOUT_26 *input_4, uint32_t *input_5);
int32_t MpConstructSyncMonitorVariableData(int32_t input, uint16_t *input_2, int64_t *buffer, uint32_t buffer_size);
void MpReleaseSendingSyncMonitorNotification(void);
int32_t MpAcquireSendingSyncMonitorNotification(uint64_t input, int64_t *input_2);
int64_t *MpAllocateFileStateGenericTableEntry(uint64_t input, uint32_t allocation_size);
void MpDlpSearchNamedEA(uint32_t *input, uint64_t input_2, char *input_3);
void MpDlpCheckPreWriteOperation(int64_t data, void *input, void *input_2);
uint64_t MpSetTrustedInstallerHardeningExcludeFlags(uint64_t input, uint64_t input_2);
void MpTraceLogTrustedInstallerHardeningFlags(uint32_t input);
void _tlgEnableCallback(uint64_t input, int32_t input_2, uint8_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, int32_t *input_7);
void GetMpUniquePidFromProcessId(int64_t process_id, uint32_t *input);
void MpRegFreeMatchingInfo(WD_LAYOUT_20 *allocation);
uint64_t MpCreatePsThreadSyncMonitorData(int64_t input, void *input_2, int64_t input_3, int64_t input_4, uint32_t *input_5);
void MpGetThreadCreateTimeById(int64_t input, uint64_t *input_2);
void MpGetThreadCreateTimeByHandle(int64_t input, uint64_t *input_2);
void MpGetThreadWin32StartAddressById(int64_t input, int64_t input_2);
uint64_t MpTxfAddStream(void *input, void *input_2, int16_t input_3, void *context);
void MpImageVerificationCallback(uint64_t input, uint64_t input_2, void *input_3);
int32_t MpAllocateDriverInfoEx(void *input, uint64_t *input_2);
void MpSendPostMountAsyncMessage(WD_LAYOUT_47 *input);
void MpFreeObjectName(int64_t name);
void MpQueryDosName(WD_LAYOUT_45 *input, WD_LAYOUT_109 *trace_argument_2, uint32_t input_2, uint32_t *input_3);
uint64_t MpFreeProcessContext(void *context);
uint64_t MpDlpProcessClearSensitiveSectionFileList(WD_LAYOUT_7 *input);
void MpFreeCopyCache(WD_LAYOUT_8 *input);
void MpIsEmptySparseFile(void *input);
void MpGetFileCompressedFileSize(int64_t input, int64_t file_object, uint64_t *input_2);
void TlgAggregateInternalRegisteredProviderEtwCallback(uint64_t input, int32_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, void *input_7);
void LookUpTableFlushComplete(void *input);
void MpDasdWrite(WD_LAYOUT_41 *input, void *input_2, WD_LAYOUT_20 *input_3);
void MpRegpFreeDeleteKeyContext(void *input);
void MpDeleteThreadContext(uint64_t context);
void MpInstanceTeardownComplete(void);
void MpRegpFreeCreateKeyContext(void *input);
void MpStoreGoodBootSector(int16_t *trace_argument_2, uint64_t input);
void MpTxfIsFileLockByTransaction(void *input, void *input_2, char *input_3);
uint64_t MpFgAvlCompareRoutine(uint64_t input, void *input_2, void *input_3);
uint32_t MpDasdVolumeWriteNotify(WD_LAYOUT_41 *input, WD_LAYOUT_20 *input_2);
void MpSendRawVolumeWriteAsyncMessage(WD_LAYOUT_4 *input, WD_LAYOUT_10 *input_2, uint64_t input_3, uint64_t input_4, char input_5);
void MpRegpFreeSetKeySecurityContext(void *input);
uint64_t MpPowerStatusCallback(int32_t *input, int32_t *input_2, int32_t input_3);
int32_t MpSendOpenWithoutReadNotification(void);
void MpGetProcessName(int64_t input, uint64_t *input_2);
void MpGetProcessNameByHandle(int64_t input, uint64_t *input_2);
void MpConnect(uint64_t input, uint64_t *trace_argument_1, uint32_t *input_2, uint64_t *input_3, int64_t *input_4);
void MpTraceLogServiceConnectFailure(uint32_t input, uint64_t input_2, uint64_t input_3, uint8_t input_4);
void MpFsHardeningSetServiceHardeningItems(uint32_t *input, int32_t input_2);
int32_t FsHardeningItemCreate(uint16_t *source_string, uint16_t *extension, int32_t input, int32_t input_2, uint32_t input_3, int32_t input_4, int64_t *input_5);
int64_t *FsHardeningItemAllocate(uint16_t *input, uint64_t *input_2);
void MpTxfCallback(void *input, void *input_2, int32_t trace_argument_1);
uint64_t MpDlpGetNetworkRedirectionInfo(int64_t *input);
uint64_t MpBoostLowPriThreads(int32_t input, char input_2, uint64_t input_3, uint64_t input_4);
void MppBoostThread(uint64_t input, uint32_t input_2, uint32_t input_3, char input_4);
void MpIsSrvClientLocalhost(WD_LAYOUT_81 *input, int32_t input_2, int16_t *input_3, int64_t input_4, int32_t input_5, void *input_6);
void MpDisconnect(int64_t *input, uint64_t event_id);
void MpSetMonitorFlags(char input, uint64_t input_2);
void MpTraceLogRegLinkHardeningFlags(int32_t input, int32_t input_2);
uint64_t *MpQueryStatistics(void *input, uint64_t input_2);
void MpAsyncQueryStatistics(uint32_t *input, uint32_t *input_2, uint64_t *input_3, uint64_t *input_4);
void FsHardeningItemListClearUnsafe(void);
void FsHardeningItemFree(WD_LAYOUT_2 *allocation);
uint64_t MpValidateVolumeExclusionUserData(uint32_t input, void *input_2);
void MpApplyVolumeExclusions(int32_t input, uint64_t input_2, int16_t *trace_argument_1);
void MpDlpReleaseNetworkRedirectionInfo(WD_LAYOUT_106 *allocation);
int64_t *MpAllocateAndInitFileStateGenericTable(void);
uint64_t MpAppendList(WD_LAYOUT_25 *input, WD_LAYOUT_99 *input_2);
void TlgAggregateInternalProviderCallback(uint64_t input, int32_t input_2, uint64_t input_3, int64_t input_4);
void MpRemoveAllKnownBadEntries(void *input, uint64_t input_2);
void MpGetFileReparseTag(int64_t instance, int64_t file_object, uint32_t *input);
void MpDlpSetEnlightenedAppMarker(void *input, uint32_t input_2);
uint64_t MpPostFsControl(void *data, WD_LAYOUT_76 *objects, int64_t completion_context, uint32_t flags);
void MpIsFileMappedInProcess(int64_t source_name, int64_t input, uint64_t input_2);
int32_t MpSendTrustedProcessMessage(char trace_argument_1, WD_LAYOUT_10 *input);
void MpFgCreateProtectedFoldersTable(void *input, uint64_t *input_2);
int32_t MpDlpSetNetworkRedirectionInfo(int64_t input);
void MpTxfDeleteContext(void *input, uint64_t input_2);
void MpRWLAcquireShared(WD_READ_WRITE_LOCK *lock);
void MpSendCheckJournalNotification(void *input, WD_LAYOUT_76 *input_2);
void MpNriNotificationCallback(int64_t input, int32_t *input_2, int64_t input_3);
void MpRegisterThreadBoost(void *input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
uint64_t *MppFindBoostControlUnsafe(int64_t input);
uint64_t MpPackLoadedDriverInfo(void *input, uint32_t *buffer, uint32_t input_2, uint32_t *input_3);
void MpTraceLogEfsHardeningChanged(int32_t input, int32_t input_2);
void FsHardeningItemListResetToDefault(void);
void MpDlpShouldCheckMappedFileOperation(int64_t input, void *input_2, uint64_t *input_3);
void MpParseFileName(WD_UNICODE_STRING_VALUE *input, uint16_t *input_2, WD_LAYOUT_19 *input_3, WD_LAYOUT_19 *input_4, int16_t *input_5, uint16_t *input_6);
void MpMarkStreamDataChanged(uint64_t input, void *input_2, uint64_t input_3);
void MpFreeDriverInfoEx(void *allocation);
void MpRWLReleaseExclusive(WD_READ_WRITE_LOCK *lock);
void MpGetProcessFileObject(uint64_t input, int64_t *input_2, int64_t *input_3);
void MpQueryName(void *input, WD_LAYOUT_110 *trace_argument_2, uint32_t input_2, uint32_t *input_3);
void MpGetProcessCommandLineByHandle(int64_t input, uint64_t *input_2);
void MpSetFileKernelEa(int64_t input, int64_t input_2, uint32_t input_3);
void MpFreeWithTag(void *allocation, uint32_t tag);
void MpTxfUpdateStreamData(void *input, uint8_t *input_2, void *input_3);
void MpTraceDlpSyncMessageTimeout(char input, uint16_t input_2, uint16_t input_3);
void MpQueryObjectNameByHandle(int64_t handle, uint64_t name, uint64_t *name_2);
void MpReleaseThreadContext(void *context);
char MpFgAuditTableCompareRoutine(uint64_t input, void *input_2, void *input_3);
void MpTearDownFltMgr(void);
void MpAsyncCleanupQueue(void);
void MpAsyncShutdown(void);
void MpAsyncpRemoveNotificationsUnsafe(int64_t *input);
void MpAsyncScanCleanupQueue(void);
void MpAsyncScanEnqueue(void *input);
void MpAsyncScanShutdown(void);
void MpIsDeveloperVolume(uint64_t input, WD_LAYOUT_111 *input_2);
void MpDlpConnect(uint64_t input, uint64_t *trace_argument_1, uint32_t *input_2, uint64_t *input_3, int64_t *input_4);
void MpDlpDisconnect(int64_t *input, uint64_t event_id);
void MpFreeCommPorts(void);
void MpMessage(uint64_t input, int64_t input_2, uint32_t allocation_size, WD_LAYOUT_109 *trace_argument_2, uint32_t allocation_size_2, uint32_t *pool_type);
void MpDlpPostCreate(void *data, void *input, void *input_2, uint64_t *input_3, void *input_4);
uint64_t MpHandleQueryEaEcpPreCreate(WD_LAYOUT_36 *input, int64_t input_2);
void MpHardenBindFltBind(void *data, WD_LAYOUT_76 *input);
void MpPostCreate(void *data, void *objects, uint64_t *completion_context, uint64_t flags);
void MpSendBlockProcessExecMessage(uint64_t data, int32_t input);
int32_t MpSendOSCopyHintTelemetry(uint32_t input);
void MpFreeHardeningExcludeData(WD_LAYOUT_54 *allocation);
int32_t MpSendRtpTainTelemetry(int64_t input);
void MpShutdownProcessExclusions(void);
void MpDeleteBootScanContext(WD_LAYOUT_25 *allocation, uint64_t input);
uint32_t MpValidateAndReferenceBootScanDevice(int64_t object, int32_t input);
uint64_t MpWriteBootSector(void *input, uint64_t input_2, uint64_t provider);
void MpWriteRawDevice(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4);
void MpDeleteLookasideLists(void);
void MpFreeGlobals(void);
uint64_t MpQueryTeardown(void);
uint64_t MpUnload(uint64_t input);
void WppCleanupKm(void);
void WppInitKm(void);
void WppLoadTracingSupport(void);
void WppTraceCallback(uint8_t input, uint64_t input_2, uint32_t buffer_size, uint32_t *buffer, void *input_3, uint32_t *input_4);
int32_t MpPersistFilterHealthInformation(void *input);
int32_t MpSendAsyncPanicModeMessage(uint32_t input, WD_UNICODE_STRING_VALUE *input_2, char input_3, char input_4, uint32_t input_5);
void PersistFilterPanicInfoWorker(uint64_t input);
void SwitchToPanicMode(uint32_t input, WD_UNICODE_STRING_VALUE *input_2, uint32_t input_3, uint64_t input_4);
uint64_t MpAddKnownBadEntry(void *input, uint32_t input_2);
void MpDeleteBootSectorCache(void);
void MpPurgeInstanceScannedFileCache(void *trace_argument_2);
void MpRemoveGoodBootSector(int16_t *trace_argument_2, uint64_t input);
void MpCopyFileChunkOnPreWrite(WD_LAYOUT_41 *input, void *input_2);
void MpReleaseWriteContextWorker(uint64_t input, uint64_t input_2, void *input_3);
void MpTxfCleanup(void);
void MpTxfPostSavepointNotification(int64_t input, WD_LAYOUT_76 *input_2, int64_t input_3);
int32_t MpTxfPreSavepointNotification(int64_t input, uint64_t *input_2, uint64_t input_3, uint64_t input_4);
uint64_t MpTxfpValidateSavepointInfo(WD_LAYOUT_4 *input, WD_LAYOUT_100 *input_2);
void EnforceExclusionProtection(int64_t input);
void EnforceKeyProtection(int64_t input, int64_t input_2);
uint64_t MpRegHardeningCallback(uint64_t input, int32_t input_2, WD_LAYOUT_81 *input_3);
uint64_t MpRegIsTamperProtectedLevelExempt(int64_t *input);
int32_t MpRegPostRenameKey(WD_LAYOUT_70 *input, uint64_t input_2, WD_LAYOUT_116 *input_3);
int32_t MpRegPostReplaceKey(WD_LAYOUT_72 *input, uint64_t input_2, WD_LAYOUT_116 *input_3);
int32_t MpRegPostRestoreKey(WD_LAYOUT_72 *input, uint64_t input_2, WD_LAYOUT_116 *input_3);
int32_t MpRegPreQueryValueKey(WD_LAYOUT_81 *input, uint64_t input_2, uint64_t input_3);
void MpRegPreRenameKey(int64_t *input, uint64_t input_2, int64_t *input_3, char *input_4, void *input_5);
void MpRegPreReplaceKey(int64_t *input, uint64_t input_2, int64_t *input_3, char *input_4, void *input_5);
void MpRegPreRestoreKey(int64_t *input, uint64_t input_2, int64_t *input_3, char *input_4, void *input_5);
void MpRegShutdown(void);
void MpUnregisterRegCallback(void);
void MpRegFreeMonitorData(int64_t allocation);
void MpRegpFreeDestinationKeyName(int64_t allocation);
void MpRegpGetKeyDestinationName(WD_LAYOUT_82 *input, WD_UNICODE_STRING_VALUE *input_2, uint64_t *input_3);
void MpRegpAllocRenameKeyContext(void);
void MpRegpAllocSetKeySecurityContext(void);
void MpRegpFreeAllCallContextsUnsafe(void);
void MpRegpFreeRenameKeyContext(void *input);
void MpCreateSecurityHealthServiceSID(uint64_t *input);
void MpFreeServiceSID(int64_t allocation);
void MpGetMappedFileName(int64_t input, int64_t input_2, int64_t input_3);
void MpGetSymlinkFinalTarget(uint16_t *input, uint64_t *input_2);
void MpNormalizeNameUnsafe(int64_t file_object, WD_LAYOUT_113 *input, WD_UNICODE_STRING_VALUE *input_2);
void MpRemoveAdminAndNonAdminSidsFromSd(int64_t input);
void MpUsnWriteCloseRecord(uint64_t input);
void MpHashLibRelease(void);
void MpHashLibReleaseImpl(void *allocation);
void MpRWLInitialize(WD_READ_WRITE_LOCK *lock);
uint8_t MpRWLTryAcquireExclusive(WD_READ_WRITE_LOCK *lock);
void MpFsCtlGetTrustedDevVolumeProtectionLevel(void *input, WD_LAYOUT_76 *input_2);
void MpFsCtlQueryGlobalData(void *input);
uint64_t MpFsCtlQueryOsCopyAcceleratorKernelSupport(void *input);
uint64_t MpFsCtlQueryProcessInformation(void *input);
int32_t MpFsCtlQueryProcessTableInfo(void *input);
void MpFsCtlQueryStreamInformation(void *input, void *input_2);
void MpFsCtlQuerySyncMonitorInformation(void *input);
uint64_t MpFsCtlQueryTestFeatureControls(void *input);
void MpFsCtlSet1PASOOVolume(WD_LAYOUT_4 *input, void *input_2);
uint32_t MpFsCtlSetDynamicFsHardeningItems(WD_LAYOUT_4 *input);
int32_t MpFsCtlSetKernelEaFile(WD_LAYOUT_4 *input, WD_LAYOUT_50 *input_2);
uint64_t MpFsCtlSetProcessInformation(WD_LAYOUT_4 *input);
int32_t MpFsCtlSetProcessTrust(WD_LAYOUT_4 *input);
uint64_t MpFsCtlSimulateAoacState(WD_LAYOUT_4 *input, uint64_t input_2);
void MpPostSetEa(void *data, void *objects, int64_t *completion_context, uint64_t flags);
void MpPreDuplicateExtentsToFile(uint64_t input, void *input_2);
uint64_t MpPreReadRawEncrypted(WD_LAYOUT_28 *data, void *input);
void MpPreSetEa(void *data, void *objects, uint64_t *completion_context);
void MpObHipsCallback(WD_LAYOUT_61 *input, uint32_t *input_2, int32_t input_3, int32_t input_4, void *input_5, void *input_6, uint8_t *input_7, char *input_8);
void MpObShutdown(void);
uint64_t MpCopyCacheCleanup(void);
void MpCreateProcessNotifyRoutine(int64_t process_id, uint64_t process_id_2, char input, uint64_t current_thread);
void MpLoadImageNotifyRoutine(uint16_t *source_string, int64_t process_id, uint32_t *input, uint16_t *trace_argument_1);
void MpRemoveProcessNotifyRoutine(uint64_t input, uint64_t input_2);
void CsrssPreScanFilterRoutine(uint64_t data, uint64_t input, void *input_2);
void MpCreateProcessContext(uint64_t process_id, int64_t input, uint64_t *input_2, int64_t *input_3);
void MpCreateProcessContextByObject(uint64_t process, int64_t *input);
uint64_t MpCryptSvcPreScanFilterRoutine(uint64_t input, uint64_t input_2, uint64_t input_3, void *input_4);
void MpFreeCsrssHookData(int64_t *allocation);
uint64_t MpGetKnownProcessType(WD_UNICODE_STRING_ADDRESS_VIEW *source_string, uint32_t *trace_argument_3, uint64_t ignore_case);
int32_t MpGetProcessBlockExecStatus(WD_LAYOUT_27 *input);
void MpIsCryptServiceProcess(void *input, int64_t input_2);
void MpReleaseProcessContextList(int64_t *input);
void MpSetCsrssPreScanFilterRoutine(int64_t input, void *trace_argument_2, int16_t *input_2);
void MpSetProcessPreScanFilterRoutine(int64_t input, void *trace_argument_2, int16_t *input_2);
void MpShutdownProcessTable(void);
void MpSystemPreScanFilterRoutine(void *data, uint64_t input, void *input_2, void *input_3);
void MpCleanupDocOpenRules(void);
void MpSendDocOpenMessage(uint64_t input, uint64_t source_text, WD_LAYOUT_10 *input_2, void *input_3);
void MpCleanupDriverInfo(void);
void MpRemoveImageVerificationCallback(void);
uint32_t MpSeqDetectCtxAllocResources(void);
void MpPreAcquireSectionSync(void *data, void *objects);
void MpPowerStatusUninitialize(int64_t input);
void MpClearBoostControlList(void);
void MpShutdownBoostManager(void);
uint64_t MpCopyCsvStreamStateFromCacheEntry(void *input, void *input_2);
void MpReadCsvRevisionECP(uint64_t input, uint64_t *input_2);
uint64_t MpSaveCsvStreamStateToCacheEntry(void *input, uint32_t input_2, void *input_3);
uint8_t MpCopyRefsStreamStateFromCacheEntry(WD_STREAM_STATE *stream, const WD_CACHE_ENTRY *entry);
uint8_t MpSaveRefsStreamStateToCacheEntry(const WD_STREAM_STATE *stream, uint32_t size, WD_CACHE_ENTRY *entry);
uint8_t MpCopyNtfsStreamStateFromCacheEntry(WD_STREAM_STATE *stream, const WD_CACHE_ENTRY *entry);
uint8_t MpSaveNtfsStreamStateToCacheEntry(const WD_STREAM_STATE *stream, uint32_t size, WD_CACHE_ENTRY *entry);
void MpDumpUntrustedProcesses(void);
void MpRefreshProcessNotifications(void);
void FgSendEventsWorker(uint64_t input, uint64_t input_2, void *input_3);
void MpFgAuditShutdown(void);
int64_t *MpFgAvlAllocateRoutine(uint64_t input, uint32_t allocation_size);
void MpFgAvlFreeRoutine(uint64_t input, int64_t allocation);
void MpFgCleanup(uint64_t input, uint64_t input_2);
uint16_t *MpDlpCheckOperation(int64_t data, WD_LAYOUT_39 *input, void *input_2, uint32_t input_3, uint32_t input_4, uint16_t *input_5, uint32_t *input_6);
void MpDlpCleanupMappedFileNamesArray(void *input);
void MpDlpCopyPolicyToDestination(WD_LAYOUT_88 *input, int16_t *input_2);
uint64_t MpDlpDetermineServiceQueryParameters(uint32_t input, int32_t *input_2, char *input_3, int64_t *input_4, int64_t *input_5, uint32_t *input_6);
void MpDlpDeviceCallback(uint64_t input, int32_t *input_2, WD_LAYOUT_121 *input_3);
void MpDlpDeviceCallbackOnDeviceAccess(int32_t *input, WD_LAYOUT_120 *input_2);
void MpDlpDeviceCallbackOnDeviceArrival(int32_t *input, WD_LAYOUT_121 *input_2);
void MpDlpDeviceCallbackOnDeviceRemoval(int32_t *input, WD_LAYOUT_121 *input_2);
void MpDlpDeviceCallbackOnEnumerateDevice(int32_t *input, WD_LAYOUT_122 *input_2);
uint64_t MpDlpFreeDeviceAccessServiceMessageRequest(int64_t allocation);
void MpDlpGetOsDependentEnlightmentFlags(uint32_t *input);
uint64_t MpDlpInitializeEnlightenment(void);
uint64_t MpDlpInitializeSystemFolders(void);
int64_t MpDlpIsExtSupported(int32_t input);
void MpDlpQueryEaByName(int64_t input, WD_LAYOUT_32 *input_2, char *input_3);
uint64_t MpDlpReallocMappedFileNamesArray(WD_LAYOUT_38 *input, uint32_t allocation_size);
void MpDlpSendOnDeviceAccessServiceMessage(uint64_t input, WD_LAYOUT_119 *input_2, uint32_t *input_3, uint32_t *input_4);
void MpDlpSendOnDeviceArrivalServiceMessage(WD_LAYOUT_121 *input);
void MpDlpSendOnDeviceEnumerationServiceMessage(WD_LAYOUT_121 *input);
void MpDlpSendOnDeviceRemovalServiceMessage(WD_LAYOUT_121 *input);
void MpDlpSendServiceMessage(uint64_t input, void *input_2, WD_LAYOUT_51 *input_3);
int32_t MpDlpSendServiceMessageTest(void);
uint64_t MpDlpSerializeDeviceAccessServiceMessageRequest(void *input, WD_LAYOUT_119 *input_2, uint64_t *input_3);
uint64_t MpDlpSerializeDeviceInformationServiceMessageRequest(int32_t input, void *input_2, uint64_t *input_3);
void MpDlpShutdown(void);
void MpShutdownThreadTable(void);
void MpQueryLoopbackLocalPathByName(void *input, void *file_name, int64_t *input_2, uint64_t *input_3);
uint64_t MpGetInstanceFromFileHandle(int64_t input, int64_t *input_2, int64_t *input_3, uint64_t input_4);
void MpGetInstanceFromVolumeName(uint64_t input, uint64_t *input_2);
void MpDlpDeleteNetworkRedirectionInfo(void);
void MpSetEaForNetworkFileStubIfNeeded(WD_LAYOUT_4 *data, void *input, char *input_2);
uint64_t MpFsHardeningInitialize(void);
void MpFsHardeningRelease(void);
void MpObRundownRelease(void);
void MpTraceFsHardeningNotification(char input, char input_2, WD_LAYOUT_77 *input_3, void *input_4, uint32_t *input_5, char input_6);
void MpTraceLogDriverEntryFailure(uint32_t input);
void MpTraceLogInitialize(void);
void MpTraceLogRelease(void);
void MpTraceObRefLeak(uint64_t input);
void MpTracePPLRedux(WD_LAYOUT_89 *input, void *input_2, uint32_t input_3, char input_4);
void TraceLoggingRegisterEx_EtwRegister_2K(void *input);
void CancelTimerCallbacksAndDeleteTimer(void *input, uint64_t input_2, uint64_t input_3);
int32_t ComputeFlushPeriod(uint64_t input);
int64_t *CreateTlgAggregateSession(bool input, bool input_2);
void DestroyAggregateSession(WD_LAYOUT_85 *allocation);
void FlushEventEntryList(uint64_t input, void *input_2);
void LookUpTableFlushPartial(void *input);
void TlgAggregateInternalFlushWorkItemRoutineKernelMode(void *input);
void UpdateInternalStatsOnFlush(void *input, uint32_t input_2);
uint64_t TlgRegisterAggregateProviderEx(WD_LAYOUT_123 *input, uint64_t input_2);
void TlgUnregisterAggregateProvider(WD_LAYOUT_114 *input, uint64_t input_2);
void TraceLoggingRegisterEx_EtwRegister_EtwSetInformation(void *input, uint64_t input_2, uint64_t input_3);
void MpCreateCallback(int64_t input);
void MpGetParentProcessByObject(int64_t input, int64_t process);
void MpGetProcessCommandLineByPointer(int64_t input, uint64_t *input_2);
void MpGetProcessNameByObject(int64_t input, uint64_t *input_2);
uint32_t MpRegisterCallback(int64_t input, int64_t input_2, uint64_t input_3, int64_t *input_4);
int16_t *MpFindUnicodeSubstring(WD_UNICODE_STRING_VALUE *string);
void MpFreeKeyData(int64_t allocation);
void MpQueryRegDword(uint64_t input, uint64_t input_2, uint32_t *input_3);
void MpQueryValueKey(uint64_t key_handle, uint64_t value_name, uint64_t input, uint64_t *input_2, uint32_t *input_3);
bool MpAsyncSendNotification__filter_0(uint64_t *input);
void MpPreCleanup__finally_0(uint64_t input, void *input_2);
void MpDlpPreCleanup__finally_0(uint64_t input, void *input_2);
void MpAmPostCreate__finally_0(uint64_t input, void *input_2);
void MpUpdateHandleContextOnPostCreate__finally_0(uint64_t input, void *input_2);
void MpCreateHandleContext__finally_0(uint64_t input, void *input_2);
void MpCreateStreamContext__finally_0(uint64_t input, void *input_2);
void MpDlpSetEaOnDestination__finally_0(uint64_t input, void *input_2);
void MpCopyCacheOnPostCreate__finally_0(uint64_t input, void *input_2);
void MpFgSendNotification__finally_0(void);
void MpCreateInstanceContext__finally_0(uint64_t input, void *input_2, uint64_t provider);
void MpScanBootSector__finally_0(uint64_t input, void *input_2);
void MpGetInstanceFromFileObject__finally_0(uint64_t input, void *input_2);
void MpSaveStreamStateToFileStateGenericTable__finally_0(uint64_t input, void *input_2);
void MpPreQueryEa__finally_0(uint64_t input, void *input_2);
void MpQueryEaFromNetworkFileStubIfNeeded__finally_0(uint64_t input, void *input_2);
void MpConnect__finally_0(uint64_t input, void *input_2);
void MpDlpSetNetworkRedirectionInfo__finally_0(uint64_t input, void *input_2);
bool MpAsyncScanEnqueue__filter_0(uint64_t *input);
void MpDlpConnect__finally_0(uint64_t input, void *input_2);
void MpPostSetEa__finally_0(uint64_t input, void *input_2);
void MpPreSetEa__finally_0(uint64_t input, void *input_2);
void MpGetInstanceFromFileHandle__finally_0(uint64_t input, void *input_2);
void MpSetEaForNetworkFileStubIfNeeded__finally_0(uint64_t input, void *input_2);
void MpVerifyWindowsVersion(uint32_t input, uint32_t input_2, int16_t input_3, uint64_t input_4, int32_t input_5);
void MpAsyncInitialize(void);
void GsDriverEntry(WD_LAYOUT_124 *driver_object, WD_UNICODE_STRING_VALUE *registry_path);
void __security_init_cookie(void);
void MpAsyncScanInitialize(void);
int32_t MpCreateCommPorts(uint64_t input, uint64_t input_2);
void MpCreatePort(uint64_t input, uint64_t input_2, uint64_t input_3, uint64_t input_4, uint64_t input_5, uint64_t input_6, uint64_t input_7);
int32_t MpCreateSecurityDescriptor(uint64_t input, uint64_t input_2, uint64_t *input_3, uint64_t input_4);
void MpSetBufferLimits(void);
uint64_t MpInitializeProcessExclusions(void);
void DriverEntry(WD_LAYOUT_124 *driver_object, WD_UNICODE_STRING_VALUE *registry_path);
void MpGetSystemRoutines(void);
int32_t MpInitializeFltMgr(WD_LAYOUT_124 *input, uint64_t input_2);
void MpInitializeGlobals(WD_LAYOUT_124 *driver_object, WD_UNICODE_STRING_VALUE *registry_path);
void MpInitializeLookasideLists(void);
void MpIsDriverVerified(uint32_t *input);
void MpLoadRegistryParameters(void);
void MpSetDefaultConfigs(void);
uint64_t MpInitBootSectorCache(void);
uint64_t MpTxfInitialize(void);
void MpRegCreateHardeningList(void);
void MpRegInitialize(void);
int32_t MpRegisterRegCallback(void);
void MpCreateCoreServiceSID(int64_t *input);
void MpCreateCryptServiceSID(int64_t *input);
void MpCreateMpDlpServiceSID(int64_t *input);
void MpCreateMpServiceSID(int64_t *input);
void MpCreateNriServiceSID(int64_t *input);
void MpCreateTrustedInstallerSID(int64_t *input);
void MpObAddCallback(uint64_t *input);
void MpObInitialize(void);
int32_t MpSetProcessNotifyRoutine(void);
int64_t MpInitializeProcessTable(void);
void MpUpdateRunningProcesses(uint64_t input, uint64_t input_2);
uint64_t MpInitializeDocOpenRules(void);
uint64_t MpInitializeDriverInfo(void);
void MpSetImageVerificationCallback(void);
void MpSeqDetectCtxInitialize(uint64_t input, uint64_t input_2);
int32_t MpPowerStatusInitialize(uint64_t *input);
void MpInitializeBoostManager(void);
uint64_t MpFgInitialize(void);
int32_t MpDlpInitialize(void);
uint64_t MpInitializeThreadTable(void);
void MpAsyncInitialize__finally_0(uint64_t input, void *input_2);
void MpAsyncScanInitialize__finally_0(uint64_t input, void *input_2);
void MpCreateCommPorts__finally_0(uint64_t input, void *input_2);
void MpCreateSecurityDescriptor__finally_0(uint64_t input, void *input_2);
void DriverEntry__finally_0(uint64_t input, void *input_2);
void MpIsDriverVerified__finally_0(uint64_t input, void *input_2);

#define WPP_SF_qDL WPP_SF_qDD
#define WPP_SF_qLL WPP_SF_qDD

#endif
